### PR TITLE
Add Token Options

### PR DESCRIPTION
**Pull request by rkillackey**
Adds `options` to token for token context.

Still need to add tests for `header_token`, but figured you could take a look in the meantime!

### CODE REVIEW

**Review by davemcorwin — CHANGES_REQUESTED** [review]
Logic generally looks ok, some thoughts on the implementation below:

1. AuthToken - In the current implementation, I'm not seeing the benefit of having a class to represent this. The goal is to return a token from either a cookie or a header, it seems like a plain ol method would suffice since this we're not passing this AuthToken around and encapsulating some data/logic. It looks like the only difference is that one could potentially have BOTH a cookie and header token, but this isn't used nor is it a feature that we care about necessarily.

2. Tests - I think the tests could be a bit clearer by being more explicit and consistent about the arguments. For example, the defined data should be the 2 types of cookies and the 2 types of headers, instead of specifying them differently. In the first example the cookie is assembled from some data while in the second example, the cookie is already assembled. So we could define `cookie_obj`, `cookie_str`, `header_obj`, and `header_str` (names not important) that would directly correspond to each test example.

3. As is, this will just start returning an object so it has the potential to break the client. I haven't looked at the changes to `lp-redux-api`, is this handled there?

**Comment by rkillackey** [comment]
@davemcorwin Updated to move all the token logic back to the controller. Having some trouble with the tests, specifically trying mock the `cookies` and `request` objects, however.

**Review by davemcorwin — COMMENTED** [review]
how about:
```
def cookie_token
  parse_token(cookies[:lp_auth])
end

def header_token
  parse_token(fetch_header_auth)
end

def fetch_header_auth
  request_headers.fetch('Authorization', '').split(' ').last
end

def parse_token(token_path)
  return nil unless token_path
  begin
    parsed = JSON.parse(token_path)
    parsed.fetch('token', nil)
  rescue JSON::ParserError
    token_path
  end
end
```

**Comment by rkillackey** [comment]
@davemcorwin Ready for another look! Tests are updated. I also did some testing with the header token locally, and it looks like it is getting set correctly (it's being stringified as with `cookies`).

**Review by davemcorwin — APPROVED** [review]

**Pull request merged**
